import 'package:flutter/material.dart';
import 'package:simple_icons/simple_icons.dart';

class TechStackIcons {
  static final Map<String, IconData> map = {
    // Languages
    'Dart': SimpleIcons.dart,
    'Flutter': SimpleIcons.flutter,
    'Java': SimpleIcons.openjdk,
    'Kotlin': SimpleIcons.kotlin,
    'Swift': SimpleIcons.swift,
    'JavaScript': SimpleIcons.javascript,
    'TypeScript': SimpleIcons.typescript,
    'Python': SimpleIcons.python,
    'Go': SimpleIcons.go,
    'Rust': SimpleIcons.rust,
    'C++': SimpleIcons.cplusplus,
    // 'C#': SimpleIcons.csharp, // Not found
    'PHP': SimpleIcons.php,
    'Ruby': SimpleIcons.ruby,
    'C': SimpleIcons.c,
    'R': SimpleIcons.r,
    'Scala': SimpleIcons.scala,
    'Haskell': SimpleIcons.haskell,
    'Lua': SimpleIcons.lua,
    'Shell': SimpleIcons.gnubash,
    'Solidity': SimpleIcons.solidity,
    'Ethereum': SimpleIcons.ethereum,
    'Bitcoin': SimpleIcons.bitcoin,
    'Web3.js': SimpleIcons.web3dotjs,
    'Polygon': SimpleIcons.polygon,
    'Elixir': SimpleIcons.elixir,
    'Clojure': SimpleIcons.clojure,
    'Julia': SimpleIcons.julia,
    // 'PowerShell': SimpleIcons.powershell, // Not found
    'HTML5': SimpleIcons.html5,
    'CSS3': SimpleIcons.css3,

    // Frameworks & Libraries
    'React': SimpleIcons.react,
    'Vue.js': SimpleIcons.vuedotjs,
    'Angular': SimpleIcons.angular,
    'Node.js': SimpleIcons.nodedotjs,
    'Express': SimpleIcons.express,
    'NestJS': SimpleIcons.nestjs,
    'Laravel': SimpleIcons.laravel,
    'Django': SimpleIcons.django,
    'Flask': SimpleIcons.flask,
    'Spring Boot': SimpleIcons.springboot,
    'ASP.NET': SimpleIcons.dotnet,
    'Svelte': SimpleIcons.svelte,
    'Next.js': SimpleIcons.nextdotjs,
    'Nuxt.js': SimpleIcons.nuxt,
    'GraphQL': SimpleIcons.graphql,
    'Apollo': SimpleIcons.apollographql,
    'Redux': SimpleIcons.redux,
    'jQuery': SimpleIcons.jquery,
    'Sass': SimpleIcons.sass,
    'Tailwind CSS': SimpleIcons.tailwindcss,
    'Vite': SimpleIcons.vite,
    'Bootstrap': SimpleIcons.bootstrap,
    'Webpack': SimpleIcons.webpack,
    'Babel': SimpleIcons.babel,
    'Three.js': SimpleIcons.threedotjs,
    'Prisma': SimpleIcons.prisma,
    'TypeORM': SimpleIcons.typeorm,
    'Sequelize': SimpleIcons.sequelize,
    'Fastify': SimpleIcons.fastify,
    'Jest': SimpleIcons.jest,
    'Cypress': SimpleIcons.cypress,
    'Selenium': SimpleIcons.selenium,
    'Mocha': SimpleIcons.mocha,
    'Jasmine': SimpleIcons.jasmine,
    'Puppeteer': SimpleIcons.puppeteer,

    // Databases
    'MySQL': SimpleIcons.mysql,
    'PostgreSQL': SimpleIcons.postgresql,
    'MongoDB': SimpleIcons.mongodb,
    'MariaDB': SimpleIcons.mariadb,
    'Cassandra': SimpleIcons.apachecassandra,
    'Elasticsearch': SimpleIcons.elasticsearch,
    'Firebase': SimpleIcons.firebase,
    'Supabase': SimpleIcons.supabase,
    'Redis': SimpleIcons.redis,
    'SQLite': SimpleIcons.sqlite,
    // 'Oracle': SimpleIcons.oracle, // Not found

    // Tools & DevOps
    'Jenkins': SimpleIcons.jenkins,
    'CircleCI': SimpleIcons.circleci,
    'Travis CI': SimpleIcons.travisci,
    'Vercel': SimpleIcons.vercel,
    'Netlify': SimpleIcons.netlify,
    'Heroku': SimpleIcons.heroku,
    'DigitalOcean': SimpleIcons.digitalocean,
    'Postman': SimpleIcons.postman,
    'Insomnia': SimpleIcons.insomnia,
    // 'Adobe XD': SimpleIcons.adobexd, // Not found
    // 'Adobe Photoshop': SimpleIcons.adobephotoshop, // Not found
    // 'Adobe Illustrator': SimpleIcons.adobeillustrator, // Not found
    'Sketch': SimpleIcons.sketch,
    'Canva': SimpleIcons.canva,
    'Blender': SimpleIcons.blender,
    'Inkscape': SimpleIcons.inkscape,
    // CMS & E-commerce
    'WordPress': SimpleIcons.wordpress,
    'Shopify': SimpleIcons.shopify,
    // 'Magento': SimpleIcons.magento, // Not found
    'Strapi': SimpleIcons.strapi,
    'Joomla': SimpleIcons.joomla,
    'Drupal': SimpleIcons.drupal,

    // Game Dev
    'Godot': SimpleIcons.godotengine,

    // Platforms
    // 'Windows': SimpleIcons.windows11, // Not found
    'macOS': SimpleIcons.macos,
    'Linux': SimpleIcons.linux,

    // Data Science
    'Scikit-learn': SimpleIcons.scikitlearn,
    // 'Matplotlib': SimpleIcons.matplotlib, // Not found
    'Keras': SimpleIcons.keras,
    'Hadoop': SimpleIcons.apachehadoop,
    'Spark': SimpleIcons.apachespark,
    // 'VS Code': SimpleIcons.visualstudiocode, // Not found
    'IntelliJ': SimpleIcons.intellijidea,
    'Unity': SimpleIcons.unity,
    'Unreal Engine': SimpleIcons.unrealengine,
    'TensorFlow': SimpleIcons.tensorflow,
    'PyTorch': SimpleIcons.pytorch,
    'Pandas': SimpleIcons.pandas,
    'NumPy': SimpleIcons.numpy,
    'Git': SimpleIcons.git,
    'GitHub': SimpleIcons.github,
    'GitLab': SimpleIcons.gitlab,
    'Docker': SimpleIcons.docker,
    'Kubernetes': SimpleIcons.kubernetes,
    'AWS': SimpleIcons.amazon,
    'Google Cloud': SimpleIcons.googlecloud,
    // 'Azure': SimpleIcons.microsoft, // Not found
    'Figma': SimpleIcons.figma,
    'Jira': SimpleIcons.jira,
    'Trello': SimpleIcons.trello,
    'Slack': SimpleIcons.slack,
    'Notion': SimpleIcons.notion,
    // 'Linux': SimpleIcons.linux, // Duplicate
    'Android': SimpleIcons.android,
    'iOS': SimpleIcons.ios,
  };

  // Mapping colors for tech stacks
  static final Map<String, Color> colorMap = {
    'Dart': const Color(0xFF0175C2),
    'Flutter': const Color(0xFF02569B),
    'Java': const Color(0xFF007396),
    'Kotlin': const Color(0xFF7F52FF),
    'Swift': const Color(0xFFF05138),
    'JavaScript': const Color(0xFFF7DF1E),
    'TypeScript': const Color(0xFF3178C6),
    'Python': const Color(0xFF3776AB),
    'Go': const Color(0xFF00ADD8),
    'Rust': const Color(0xFF000000),
    'C++': const Color(0xFF00599C),
    'PHP': const Color(0xFF777BB4),
    'Ruby': const Color(0xFFCC342D),
    'C': const Color(0xFFA8B9CC),
    'R': const Color(0xFF276DC3),
    'Scala': const Color(0xFFDC322F),
    'Haskell': const Color(0xFF5D4F85),
    'Lua': const Color(0xFF2C2D72),
    'Shell': const Color(0xFF4EAA25),
    'PowerShell': const Color(0xFF5391FE),
    'Solidity': const Color(0xFF363636),
    'Ethereum': const Color(0xFF3C3C3D),
    'Bitcoin': const Color(0xFFF7931A),
    'Web3.js': const Color(0xFFF16822),
    'Polygon': const Color(0xFF7950DD),
    'Elixir': const Color(0xFF4E2A8E),
    'Clojure': const Color(0xFF5881D8),
    'Julia': const Color(0xFF9558B2),
    'HTML5': const Color(0xFFE34F26),
    'CSS3': const Color(0xFF1572B6),
    'React': const Color(0xFF61DAFB),
    'Vue.js': const Color(0xFF4FC08D),
    'Angular': const Color(0xFFDD0031),
    'Node.js': const Color(0xFF339933),
    'Express': const Color(0xFF000000),
    'NestJS': const Color(0xFFE0234E),
    'Laravel': const Color(0xFFFF2D20),
    'Django': const Color(0xFF092E20),
    'Flask': const Color(0xFF000000),
    'Spring Boot': const Color(0xFF6DB33F),
    'ASP.NET': const Color(0xFF512BD4),
    'Svelte': const Color(0xFFFF3E00),
    'Next.js': const Color(0xFF000000),
    'Nuxt.js': const Color(0xFF00C58E),
    'GraphQL': const Color(0xFFE10098),
    'Apollo': const Color(0xFF311C87),
    'Redux': const Color(0xFF764ABC),
    'jQuery': const Color(0xFF0769AD),
    'Sass': const Color(0xFFCC6699),
    'Tailwind CSS': const Color(0xFF06B6D4),
    'Vite': const Color(0xFF646CFF),
    'Webpack': const Color(0xFF8DD6F9),
    'Babel': const Color(0xFFF9DC3E),
    'Three.js': const Color(0xFF000000),
    'Prisma': const Color(0xFF2D3748),
    'TypeORM': const Color(0xFFE535AB),
    'Sequelize': const Color(0xFF52B0E7),
    'Fastify': const Color(0xFF000000),
    'Jest': const Color(0xFFC21325),
    'Cypress': const Color(0xFF17202C),
    'Selenium': const Color(0xFF43B02A),
    'Mocha': const Color(0xFF8D6748),
    'Jasmine': const Color(0xFF8A4182),
    'Puppeteer': const Color(0xFF40B5A4),
    'Bootstrap': const Color(0xFF7952B3),
    'MySQL': const Color(0xFF4479A1),
    'PostgreSQL': const Color(0xFF4169E1),
    'MongoDB': const Color(0xFF47A248),
    'MariaDB': const Color(0xFF003545),
    'Cassandra': const Color(0xFF1287B1),
    'Elasticsearch': const Color(0xFF005571),
    'Firebase': const Color(0xFFFFCA28),
    'Supabase': const Color(0xFF3ECF8E),
    'Redis': const Color(0xFFDC382D),
    'SQLite': const Color(0xFF003B57),
    'Jenkins': const Color(0xFFD24939),
    'CircleCI': const Color(0xFF343434),
    'Travis CI': const Color(0xFF3EAAAF),
    'Vercel': const Color(0xFF000000),
    'Netlify': const Color(0xFF00C7B7),
    'Heroku': const Color(0xFF430098),
    'DigitalOcean': const Color(0xFF0080FF),
    'Postman': const Color(0xFFFF6C37),
    'Insomnia': const Color(0xFF4000BF),
    'VS Code': const Color(0xFF007ACC),
    'IntelliJ': const Color(0xFF000000),
    'Unity': const Color(0xFF000000),
    'Unreal Engine': const Color(0xFF0E1128),
    'TensorFlow': const Color(0xFFFF6F00),
    'PyTorch': const Color(0xFFEE4C2C),
    'Pandas': const Color(0xFF150458),
    'NumPy': const Color(0xFF013243),
    'Git': const Color(0xFFF05032),
    'GitHub': const Color(0xFF181717),
    'GitLab': const Color(0xFFFC6D26),
    'Docker': const Color(0xFF2496ED),
    'Kubernetes': const Color(0xFF326CE5),
    'AWS': const Color(0xFFFF9900),
    'Google Cloud': const Color(0xFF4285F4),
    'Figma': const Color(0xFFF24E1E),
    'Adobe XD': const Color(0xFFFF61F6),
    'Adobe Photoshop': const Color(0xFF31A8FF),
    'Adobe Illustrator': const Color(0xFFFF9A00),
    'Sketch': const Color(0xFFF7B500),
    'Canva': const Color(0xFF00C4CC),
    'WordPress': const Color(0xFF21759B),
    'Shopify': const Color(0xFF7AB55C),
    'Magento': const Color(0xFFEE672F),
    'Strapi': const Color(0xFF2F2E8F),
    'Joomla': const Color(0xFF5091CD),
    'Drupal': const Color(0xFF0678BE),
    'Godot': const Color(0xFF478CBF),
    'Windows': const Color(0xFF0078D6),
    'macOS': const Color(0xFF000000),
    'Scikit-learn': const Color(0xFFF7931E),
    'Matplotlib': const Color(0xFF11557C),
    'Keras': const Color(0xFFD00000),
    'Hadoop': const Color(0xFF66CCFF),
    'Spark': const Color(0xFFE25A1C),
    'Jira': const Color(0xFF0052CC),
    'Trello': const Color(0xFF0052CC),
    'Slack': const Color(0xFF4A154B),
    'Notion': const Color(0xFF000000),
    'Linux': const Color(0xFFFCC624),
    'Android': const Color(0xFF3DDC84),
    'iOS': const Color(0xFF000000),
  };

  static Color getColor(String name) {
    if (colorMap.containsKey(name)) return colorMap[name]!;

    final lowerName = name.toLowerCase();
    final entry = colorMap.entries.firstWhere(
      (e) => e.key.toLowerCase() == lowerName,
      orElse: () => const MapEntry('', Colors.grey),
    );

    return entry.value != Colors.grey ? entry.value : Colors.grey;
  }

  static IconData getIcon(String name) {
    if (map.containsKey(name)) return map[name]!;

    final lowerName = name.toLowerCase();
    final entry = map.entries.firstWhere(
      (e) => e.key.toLowerCase() == lowerName,
      orElse: () => const MapEntry('', Icons.code),
    );

    return entry.value != Icons.code ? entry.value : Icons.code;
  }
}
